### ISSUE TITLE
Element change error, plz help

### ISSUE THREAD

**Issue by ItsCansuse** [Penelopeep/SwitchElementTraveller#11]
Restarted this, using the latest release as of now, and this is the error that i get

15:46:54 <INFO:CommandMap> Command used by [Cansuse - 10001]: se dendro
15:46:54 <ERROR:CommandMap> Error Command se:
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void emu.grasscutter.game.avatar.Avatar.setSkillDepotData(emu.grasscutter.data.excels.AvatarSkillDepotData)'
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:339)
        at emu.grasscutter.game.chat.ChatSystem.tryInvokeCommand(ChatSystem.java:48)
        at emu.grasscutter.game.chat.ChatSystem.sendPrivateMessage(ChatSystem.java:152)
        at emu.grasscutter.server.packet.recv.HandlerPrivateChatReq.handle(HandlerPrivateChatReq.java:21)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:86)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:207)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:73)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.NoSuchMethodError: 'void emu.grasscutter.game.avatar.Avatar.setSkillDepotData(emu.grasscutter.data.excels.AvatarSkillDepotData)'
        at test.gc.switchele.commands.SwitchElement.changeAvatarElement(SwitchElement.java:41)
        at test.gc.switchele.commands.SwitchElement.execute(SwitchElement.java:93)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:334)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        ... 1 common frames omitted

**Comment by Penelopeep** [comment]
What gc version are you using?

**Comment by ItsCansuse** [comment]
i am using alpine gc 3.4 00fd6d2 based Grasscutter

**Comment by Penelopeep** [comment]
Can you send me a link, because it probably has it included into other command (you can always try `prop se dendro`, maybe it'll work).
Otherwise I have to make some changes for it to work.

**Comment by ItsCansuse** [comment]
ok let me try that cmd

**Comment by ItsCansuse** [comment]
It worked! thank you very much
