### ISSUE TITLE
Not available in the latest version.

### ISSUE THREAD

**Issue by yuanshengaoshou114** [Penelopeep/SwitchElementTraveller#12]
（My translation may not be accurate. In the latest version, element switching and team merging don't work.）java.lang.NoSuchMethodError: 'emu.grasscutter.plugin.api.ServerHook test.gc.switchele.Switchele.getHandle()'
        at test.gc.switchele.Switchele.onEnable(Switchele.java:80)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:218)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:214)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:173)

**Comment by HELPMEEADICE** [comment]
In the latest version, Grasscutter has updated the api of the plugin.
As a result, many of the old plugins are no longer available.

**Comment by Penelopeep** [comment]
I'm fully aware of it, it was announced about a week ago, I'm planning to update all my plugins soon

**Comment by JustRad123** [comment]
> I'm fully aware of it, it was announced about a week ago, I'm planning to update all my plugins soon

well that aged well

**Comment by Penelopeep** [comment]
Like a fine wine :D
